---
haproxyTemplateFile: haproxy.cfg.j2

backendInventory: hostGcpPrivate

packageList:
  - haproxy

filesToCopy:
  - name: healthMonitor.sh
    destPath: /tmp
    mode: u=rwx
  - name: healthMonitor.py
    destPath: /tmp
    mode: u=rwx,g=r,o=r

frontends:
  - name: avivs
    # ip: 2.1.1.50
    port: 443
    backend: aviback
    mode: tcp

backends:
  - name: aviback
    balance: first
    servers:
      - name: avi1
        ip: 172.16.1.33
        port: 443
      - name: avi2
        ip: 172.16.1.34
        port: 443
      - name: avi3
        ip: 172.16.1.35
        port: 443

# routes:
#   - cidr: 10.1.1.2/32
#     nexthop: 2.1.1.20


# ifconfig:
#   - iface: ens33
#     cidr: 2.1.1.50/8
#   - iface: ens34
#     cidr: 172.16.1.11/24

# pythonScript: aviMonitor.py

# hostInventory: hostGcpPrivate
#
# defaultHaproxyConfig: haproxy.cfg
